server:
  port: 8781

spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: 
    max-active: 8
    max-idle: 8
    max-wait: -1
    min-idle: 0
    port: 6379
    timeout: 0

  datasource:
    schema:classpath:init-sql/*.sql

  jpa:
    show-sql:true

druid:
  url: jdbc:mysql://localhost:3306/timebusker-spring?useUnicode:true&characterEncoding:utf8&autoReconnect:true&failOverReadOnly:false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: 123456
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true