server:
  port: 8782
  
spring:
  datasource:
    schema: classpath:init-sql/*.sql

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true

druid:
  url: jdbc:mysql://localhost:3306/timebusker-spring?useUnicode:true&characterEncoding:utf8&autoReconnect:true&failOverReadOnly:false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: 123456
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

