server:
  port: 8761
  
spring:
  application:
    name: microservice-registry
  profiles:
    active: native

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false